Update/v24.02.1
Start9Labs/cln-startos pull request #123
Opened 2024-03-20 04:59 UTC by Dominion5254

* Update lightning to 24.02.1 - [Release Notes](https://github.com/ElementsProject/lightning/releases/tag/v24.02.1)
  * Add Experimental 'Splicing' config option. Closes #122 
  * Replace archived 'Rebalance' plugin with 'Sling'
  * Remove archived 'Summary' plugin
  * Fix WT-Client bug
  * Add action to rescan the blockchain from a specified blockheight or depth

2024-03-26 14:11 UTC, kn0wmad requested changes

2024-03-26 18:42 UTC, Dominion5254 commented on scripts/procedures/getConfig.ts
> +              "Automatically rebalance multiple channels. This is a CLI-only tool.  <b>Default: False</b><br><b>Source:  https://github.com/daywalker90/sling</b>",
Updated to "Disabled"

2024-03-27 15:24 UTC, kn0wmad approved these changes

2024-03-29 23:00 UTC, kn0wmad commented on scripts/procedures/getConfig.ts
> +            description: "Enables support for the splicing protocol (bolt #863), allowing both parties to dynamically adjust the size a channel. These changes can be built interactively using PSBT an
I figured it was from the docs, but some of their descriptions have minor errors and typos.  Want to make sure you understand the change in the final sentence

2024-03-29 23:01 UTC, kn0wmad approved these changes

2024-03-29 23:07 UTC, merged